name: test_many_dependencies
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Sensors and maps
  sensors_plus: ^2.0.1
  location: ^4.4.0
  motion_sensors: ^0.1.0
  vector_math: ^2.1.2
  native_device_orientation: ^1.1.4
  flutter_osm_plugin: ^0.41.1

  # State management and more
  flutter_hooks: ^0.18.5+1
  go_router: ^5.1.9
  get_it: ^7.2.0

  # Data store
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.2
  json_annotation: ^4.7.0

  # User interaction and views
  share_plus: ^6.2.0
  badges: ^2.0.3
  timeago: ^3.3.0
  lottie: ^2.0.0
  dropdown_button2: ^1.9.1
  url_launcher: ^6.1.7
  youtube_player_flutter: ^8.1.1
  flutter_native_splash: ^2.2.15
  map_launcher: ^2.4.0
  flutter_svg: ^1.1.6

  # Telemetry and analytics:
  sentry_flutter: ^6.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0

  icons_launcher: ^2.0.6

  # Telemetry and analytics:
  sentry_dart_plugin: ^1.0.0-beta.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
